const sentenceDisplay = document.getElementById('sentence-display');
const inputBox = document.getElementById('input-box');
const timerDisplay = document.getElementById('timer');
const wpmDisplay = document.getElementById('wpm');
const accuracyDisplay = document.getElementById('accuracy');
const startBtn = document.getElementById('start-btn');
const resetBtn = document.getElementById('reset-btn');
const gameContainer = document.getElementById('game-container');
const subtitle = document.getElementById('subtitle');
const authStatus = document.getElementById('auth-status');
const googleSignin = document.getElementById('google-signin');
const logoutBtn = document.getElementById('logout-btn');
const syncStatus = document.getElementById('sync-status');
const instructionModal = document.getElementById('instruction-modal');
const instructionCloseBtn = document.getElementById('instruction-close-btn');
const historyList = document.getElementById('history-list');
const clearHistoryBtn = document.getElementById('clear-history-btn');

const GOOGLE_CLIENT_ID =
  '173320102736-mmmp7sgqrd78r3rjenra3ed243ap2fmc.apps.googleusercontent.com';
const APPS_SCRIPT_WEB_APP_URL =
  'https://script.google.com/macros/s/AKfycbzuwH-8OWsEFoj_zNn6KLpeQFgnv-Nw0-1dN7bA_oVMkdiz7v6qCc2vTslqaD_FPnh3/exec';
const LOCAL_HISTORY_KEY = 'typingKingHistory';
const MAX_LOCAL_HISTORY = 20;
const AUTO_REAUTH_TS_KEY = 'typingKingAutoReauthTs';
const AUTO_REAUTH_COOLDOWN_MS = 10 * 60 * 1000;

let passages = [];
let currentPassageIndex = 0;
let currentLineIndex = 0;
let wpm = 0;
let accuracy = 0;
let gameStarted = false;
let isAuthenticated = false;
let currentUserName = '';
let startTime;
let timerInterval;
let totalTypedChars = 0;
let totalCorrectTypedChars = 0;
let previousInputLength = 0;
let currentUserId = '';
let currentUserEmail = '';
let authInitialized = false;
let authInitAttempts = 0;
const MAX_AUTH_INIT_ATTEMPTS = 50;

const typingPassages = [
  {
    title: '繁體中文文章',
    text: '我們期望所有同學的創作及習作均為原作。因此，除非導師另有指定，於課堂或習作上使用生成式人工智能時，必須清晰妥當地註明，並且不應在未經思考、轉化下取用人工智能生成的內容，否則當抄襲處理。',
  },
  {
    title: 'English Article',
    text: 'We expect all creations and assignments from students to be original works. Therefore, unless otherwise specified by the instructor, the use of generative AI in class or assignments must be clearly and properly acknowledged, and content generated by AI should not be used without critical thinking and adaptation; otherwise, it will be treated as plagiarism.',
  },
];

startBtn.addEventListener('click', startGame);
resetBtn.addEventListener('click', resetGame);
logoutBtn.addEventListener('click', logout);
inputBox.addEventListener('input', checkInput);
inputBox.addEventListener('paste', (e) => {
  e.preventDefault();
});
gameContainer.addEventListener('click', (e) => {
  if (!gameStarted) return;
  if (e.target === startBtn || e.target === resetBtn) return;
  enforceNoAutoAssist();
  inputBox.focus({ preventScroll: true });
});

window.onGoogleLibraryLoad = initAuth;
initAuth();
updateAuthState();
enforceNoAutoAssist();
showInstructionModal();
renderGameHistory();

if (instructionCloseBtn) {
  instructionCloseBtn.addEventListener('click', closeInstructionModal);
}

if (clearHistoryBtn) {
  clearHistoryBtn.addEventListener('click', clearGameHistory);
}

function showInstructionModal() {
  if (!instructionModal) return;
  instructionModal.hidden = false;
}

function closeInstructionModal() {
  if (!instructionModal) return;
  instructionModal.hidden = true;
}

function initAuth() {
  if (authInitialized) return;

  if (!window.google || !window.google.accounts || !window.google.accounts.id) {
    authInitAttempts += 1;
    authStatus.textContent = '正在載入 Google OAuth SDK...';
    if (authInitAttempts < MAX_AUTH_INIT_ATTEMPTS) {
      setTimeout(initAuth, 200);
    } else {
      authStatus.textContent = 'Google OAuth SDK 載入逾時，請重新整理頁面。';
    }
    return;
  }

  if (
    !GOOGLE_CLIENT_ID ||
    GOOGLE_CLIENT_ID.startsWith('YOUR_GOOGLE_CLIENT_ID')
  ) {
    authStatus.textContent = '請先在 script.js 設定有效的 GOOGLE_CLIENT_ID。';
    return;
  }

  window.google.accounts.id.initialize({
    client_id: GOOGLE_CLIENT_ID,
    callback: handleGoogleCredential,
    auto_select: true,
    cancel_on_tap_outside: true,
  });

  window.google.accounts.id.renderButton(googleSignin, {
    theme: 'outline',
    size: 'large',
    shape: 'pill',
    width: 250,
    text: 'signin_with',
  });

  if (shouldTriggerAutoReauth()) {
    window.google.accounts.id.prompt();
    markAutoReauthTriggered();
  }

  authInitialized = true;
  authStatus.textContent = '請先使用 Google 帳號登入後再開始遊戲。';
}

function shouldTriggerAutoReauth() {
  try {
    const lastTriggered = Number(localStorage.getItem(AUTO_REAUTH_TS_KEY) || 0);
    if (!Number.isFinite(lastTriggered) || lastTriggered <= 0) {
      return true;
    }

    const elapsed = Date.now() - lastTriggered;
    return elapsed >= AUTO_REAUTH_COOLDOWN_MS;
  } catch (error) {
    return true;
  }
}

function markAutoReauthTriggered() {
  try {
    localStorage.setItem(AUTO_REAUTH_TS_KEY, String(Date.now()));
  } catch (error) {
    // Ignore storage errors and keep auth flow available.
  }
}

function handleGoogleCredential(response) {
  if (!response || !response.credential) {
    authStatus.textContent = '登入失敗，請再試一次。';
    return;
  }

  const payload = decodeJwtPayload(response.credential);
  if (!payload) {
    authStatus.textContent = '無法解析 Google 登入資訊。';
    return;
  }

  isAuthenticated = true;
  currentUserId = payload.sub || '';
  currentUserEmail = payload.email || '';
  currentUserName = payload.name || payload.email || '使用者';
  authStatus.textContent = `已登入：${currentUserName}`;
  hideSyncStatus();
  subtitle.textContent = '已驗證，準備開始雙語文章挑戰';
  updateAuthState();
}

function decodeJwtPayload(credential) {
  try {
    const tokenParts = credential.split('.');
    if (tokenParts.length < 2) return null;
    const base64 = tokenParts[1].replace(/-/g, '+').replace(/_/g, '/');
    const decoded = decodeURIComponent(
      atob(base64)
        .split('')
        .map((char) => `%${`00${char.charCodeAt(0).toString(16)}`.slice(-2)}`)
        .join('')
    );
    return JSON.parse(decoded);
  } catch (error) {
    return null;
  }
}

function logout() {
  isAuthenticated = false;
  currentUserId = '';
  currentUserEmail = '';
  currentUserName = '';
  resetGame();
  subtitle.textContent = '挑戰你的速度';
  authStatus.textContent = '請先使用 Google 帳號登入後再開始遊戲。';
  if (window.google && window.google.accounts && window.google.accounts.id) {
    window.google.accounts.id.disableAutoSelect();
  }
  updateAuthState();
}

function updateAuthState() {
  startBtn.disabled = !isAuthenticated;
  inputBox.disabled = !isAuthenticated || !gameStarted;
  logoutBtn.hidden = !isAuthenticated;
  googleSignin.hidden = isAuthenticated;
}

function showSyncStatus(message, isError = false) {
  if (!syncStatus) return;
  syncStatus.hidden = false;
  syncStatus.textContent = message;
  syncStatus.style.color = isError ? '#991b1b' : '#14532d';
}

function hideSyncStatus() {
  if (!syncStatus) return;
  syncStatus.hidden = true;
  syncStatus.textContent = '';
}

function enforceNoAutoAssist() {
  if (!inputBox) return;

  // Android keyboards and browsers may ignore a single attribute, so enforce all related flags.
  inputBox.setAttribute('autocomplete', 'new-password');
  inputBox.setAttribute('autocorrect', 'off');
  inputBox.setAttribute('autocapitalize', 'off');
  inputBox.setAttribute('spellcheck', 'false');

  inputBox.autocomplete = 'new-password';
  inputBox.autocorrect = 'off';
  inputBox.autocapitalize = 'off';
  inputBox.spellcheck = false;
}

function startGame() {
  if (gameStarted) return;
  if (!isAuthenticated) {
    authStatus.textContent = '請先完成 Google 登入。';
    return;
  }
  gameStarted = true;
  currentPassageIndex = 0;
  currentLineIndex = 0;
  wpm = 0;
  accuracy = 0;
  totalTypedChars = 0;
  totalCorrectTypedChars = 0;
  previousInputLength = 0;
  enforceNoAutoAssist();
  inputBox.disabled = false;
  inputBox.value = '';
  inputBox.focus();
  timerDisplay.textContent = `時間: 0.00s`;
  if (accuracyDisplay) {
    accuracyDisplay.textContent = `準確率: 0.00%`;
  }
  hideSyncStatus();
  loadPassages();
  displayPassage();
  startTime = new Date();
  timerInterval = setInterval(updateTimer, 1000);
}

function resetGame() {
  gameStarted = false;
  clearInterval(timerInterval);
  currentLineIndex = 0;
  enforceNoAutoAssist();
  inputBox.disabled = !isAuthenticated;
  sentenceDisplay.textContent = '';
  timerDisplay.textContent = '時間: 0.00s';
  if (accuracyDisplay) {
    accuracyDisplay.textContent = '準確率: 0.00%';
  }
  inputBox.value = '';
  totalTypedChars = 0;
  totalCorrectTypedChars = 0;
  previousInputLength = 0;
  hideSyncStatus();
  subtitle.textContent = '挑戰你的速度';
}

function loadPassages() {
  passages = typingPassages.map((passage) => ({
    ...passage,
    lines: splitPassageIntoLines(passage.text, passage.title),
  }));
}

function displayPassage() {
  sentenceDisplay.innerHTML = '';
  const currentPassage = passages[currentPassageIndex];
  const totalLines = currentPassage.lines.length;
  const currentLine = currentPassage.lines[currentLineIndex] || '';
  subtitle.textContent = `第 ${currentPassageIndex + 1} / ${
    passages.length
  } 篇 - ${currentPassage.title} - 第 ${
    currentLineIndex + 1
  } / ${totalLines} 行`;

  const lineRow = document.createElement('div');
  lineRow.className = 'passage-line active-line';

  currentLine.split('').forEach((char) => {
    const charSpan = document.createElement('span');
    charSpan.innerText = char;
    lineRow.appendChild(charSpan);
  });

  sentenceDisplay.appendChild(lineRow);
  inputBox.value = '';
  previousInputLength = 0;
  if (gameStarted) {
    inputBox.focus({ preventScroll: true });
  }
}

function checkInput() {
  if (!gameStarted) return;

  const typedValue = inputBox.value;
  const currentPassage = passages[currentPassageIndex];
  const targetLine = currentPassage.lines[currentLineIndex] || '';
  const sentenceChars = sentenceDisplay.querySelectorAll('span');
  let correctChars = 0;

  if (typedValue.length > previousInputLength) {
    const newlyTypedChars = typedValue.length - previousInputLength;
    totalTypedChars += newlyTypedChars;
    for (let i = previousInputLength; i < typedValue.length; i++) {
      if (i < targetLine.length && typedValue[i] === targetLine[i]) {
        totalCorrectTypedChars++;
      }
    }
  }
  previousInputLength = typedValue.length;

  typedValue.split('').forEach((char, index) => {
    if (index < sentenceChars.length) {
      if (char === sentenceChars[index].innerText) {
        sentenceChars[index].classList.add('correct');
        sentenceChars[index].classList.remove('incorrect');
        correctChars++;
      } else {
        sentenceChars[index].classList.add('incorrect');
        sentenceChars[index].classList.remove('correct');
      }
    }
  });

  for (let i = typedValue.length; i < sentenceChars.length; i++) {
    sentenceChars[i].classList.remove('correct', 'incorrect');
  }

  updateLiveStats();

  if (
    typedValue.length === targetLine.length &&
    correctChars === targetLine.length
  ) {
    advanceToNextLine();
  }
}

function advanceToNextLine() {
  const currentPassage = passages[currentPassageIndex];
  currentLineIndex++;

  if (currentLineIndex < currentPassage.lines.length) {
    displayPassage();
    return;
  }

  currentPassageIndex++;
  currentLineIndex = 0;

  if (currentPassageIndex < passages.length) {
    displayPassage();
    return;
  }

  endGame();
}

async function endGame() {
  gameStarted = false;
  clearInterval(timerInterval);
  inputBox.disabled = true;
  const endTime = new Date();
  const timeTaken = (endTime - startTime) / 1000; // in seconds
  timerDisplay.textContent = `時間: ${timeTaken.toFixed(2)}s`;
  const accuracyValue =
    totalTypedChars > 0 ? (totalCorrectTypedChars / totalTypedChars) * 100 : 0;
  const wpmValue =
    timeTaken > 0
      ? Math.round(totalCorrectTypedChars / 5 / (timeTaken / 60))
      : 0;
  accuracy = accuracyValue;
  wpm = wpmValue;
  if (accuracyDisplay) {
    accuracyDisplay.textContent = `準確率: ${accuracy.toFixed(2)}%`;
  }
  subtitle.textContent = '完成雙語文章挑戰';

  const score = Math.round(wpm * (accuracy / 100));
  const record = {
    userId: currentUserId,
    userName: currentUserName,
    userEmail: currentUserEmail,
    language: 'zh-TW+en',
    wpm,
    accuracy: Number(accuracy.toFixed(2)),
    durationSec: Number(timeTaken.toFixed(2)),
    score,
    passageCount: passages.length,
    playedAt: new Date().toISOString(),
  };

  saveRecordToLocalHistory(record);
  renderGameHistory();

  await saveRecordToGoogleSheet(record);
}

function getLocalHistory() {
  try {
    const raw = localStorage.getItem(LOCAL_HISTORY_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (error) {
    return [];
  }
}

function saveRecordToLocalHistory(record) {
  const history = getLocalHistory();
  history.unshift(record);
  const trimmedHistory = history.slice(0, MAX_LOCAL_HISTORY);

  try {
    localStorage.setItem(LOCAL_HISTORY_KEY, JSON.stringify(trimmedHistory));
  } catch (error) {
    showSyncStatus('本機歷史紀錄儲存失敗。', true);
  }
}

function clearGameHistory() {
  try {
    localStorage.removeItem(LOCAL_HISTORY_KEY);
    renderGameHistory();
  } catch (error) {
    showSyncStatus('無法清除本機歷史紀錄。', true);
  }
}

function renderGameHistory() {
  if (!historyList) return;

  const history = getLocalHistory();
  historyList.innerHTML = '';

  if (history.length === 0) {
    const emptyItem = document.createElement('li');
    emptyItem.className = 'history-empty';
    emptyItem.textContent = '目前沒有歷史紀錄，完成一場挑戰後會顯示在這裡。';
    historyList.appendChild(emptyItem);
    return;
  }

  history.forEach((item) => {
    const listItem = document.createElement('li');
    listItem.className = 'history-item';

    const playedAtText = formatPlayedAt(item.playedAt);
    listItem.textContent = `Time played: ${playedAtText} | Duration: ${
      item.durationSec ?? 0
    }s | WPM: ${item.wpm ?? 0}`;
    historyList.appendChild(listItem);
  });
}

function formatPlayedAt(isoString) {
  if (!isoString) return '未知時間';
  const date = new Date(isoString);
  if (Number.isNaN(date.getTime())) return '未知時間';
  return date.toLocaleString('zh-TW', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function updateTimer() {
  if (!gameStarted) return;
  updateLiveStats();
}

function updateLiveStats() {
  const timeTaken = (new Date() - startTime) / 1000;
  timerDisplay.textContent = `時間: ${timeTaken.toFixed(2)}s`;

  const accuracyValue =
    totalTypedChars > 0 ? (totalCorrectTypedChars / totalTypedChars) * 100 : 0;
  const safeTimeTaken = timeTaken >= 0.1 ? timeTaken : 0.1;
  const wpmValue = Math.round(
    totalCorrectTypedChars / 5 / (safeTimeTaken / 60)
  );

  accuracy = accuracyValue;
  wpm = wpmValue;
  if (accuracyDisplay) {
    accuracyDisplay.textContent = `準確率: ${accuracy.toFixed(2)}%`;
  }
  wpmDisplay.textContent = `WPM: ${wpm}`;
}

function splitPassageIntoLines(text, title) {
  const maxUnitsPerLine = getLineLengthLimit(title);
  return text.includes(' ')
    ? splitTextByWords(text, maxUnitsPerLine)
    : splitTextByCharacters(text, maxUnitsPerLine);
}

function getLineLengthLimit(title) {
  console.log(
    `Calculating line length limit for title: ${title}, window width: ${window.innerWidth}`
  );
  if (title === '繁體中文文章') {
    return parseInt(window.innerWidth / 18);
  }
  return parseInt(window.innerWidth / 6);
}

function splitTextByCharacters(text, maxCharsPerLine) {
  const lines = [];
  let currentLine = '';

  for (const char of text) {
    currentLine += char;
    if (currentLine.length >= maxCharsPerLine) {
      lines.push(currentLine);
      currentLine = '';
    }
  }

  if (currentLine) {
    lines.push(currentLine);
  }

  return lines;
}

function splitTextByWords(text, maxUnitsPerLine) {
  const tokens = text.match(/\S+\s*/g) || [text];
  const lines = [];
  let currentLine = '';

  tokens.forEach((token) => {
    const trimmedToken = token.trimEnd();
    const nextLine = currentLine + token;

    if (currentLine && nextLine.trimEnd().length > maxUnitsPerLine) {
      lines.push(currentLine.trimEnd());
      currentLine = token;
      return;
    }

    if (!currentLine && trimmedToken.length > maxUnitsPerLine) {
      const brokenWordLines = splitTextByCharacters(
        trimmedToken,
        maxUnitsPerLine
      );
      lines.push(...brokenWordLines.slice(0, -1));
      currentLine = brokenWordLines[brokenWordLines.length - 1];
      return;
    }

    currentLine = nextLine;
  });

  if (currentLine.trim().length > 0) {
    lines.push(currentLine.trimEnd());
  }

  return lines;
}

async function saveRecordToGoogleSheet(record) {
  if (
    !APPS_SCRIPT_WEB_APP_URL ||
    APPS_SCRIPT_WEB_APP_URL.startsWith(
      'PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE'
    )
  ) {
    showSyncStatus('尚未設定 Google Sheet Web App URL，成績未上傳。', true);
    return;
  }

  try {
    const form = new URLSearchParams();
    form.set('userId', record.userId || '');
    form.set('userName', record.userName || '');
    form.set('userEmail', record.userEmail || '');
    form.set('language', record.language || '');
    form.set('wpm', String(record.wpm ?? ''));
    form.set('accuracy', String(record.accuracy ?? ''));
    form.set('durationSec', String(record.durationSec ?? ''));
    form.set('score', String(record.score ?? ''));
    form.set('passageCount', String(record.passageCount ?? ''));

    // Apps Script Web App often requires no-cors when called from static hosting.
    await fetch(APPS_SCRIPT_WEB_APP_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
      },
      body: form.toString(),
      mode: 'no-cors',
    });

    showSyncStatus('成績已送出到 Google Sheet。');
  } catch (error) {
    showSyncStatus('成績上傳失敗，請檢查網路或 Apps Script 設定。', true);
  }
}
