git submodule add https://github.com/2223179/superbass.git portfolio/2223179/superbass
git submodule add https://github.com/2223179/leopard-print-underwear.git portfolio/2223179/leopard-print-underwear
git submodule add https://github.com/2223179/funny-gamee.git portfolio/2223179/funny-gamee
git submodule add https://github.com/2223179/funny-game.git portfolio/2223179/funny-game
git submodule add https://github.com/2223179/photo2pdf.git portfolio/2223179/photo2pdf
git submodule add https://github.com/2223179/chatroom.git portfolio/2223179/chatroom
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W13_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W13_Cami
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W12_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W12_Cami
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W10_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W10_Cami
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W8_2.0_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W8_2.0_Cami
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W9_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W9_Cami
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W8_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W8_Cami
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W07_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W07_Cami
git submodule add https://github.com/2223107-cami/2223107_ICT_AI_W7_Cami.git portfolio/2223107-cami/2223107_ICT_AI_W7_Cami
git submodule add https://github.com/2223107-cami/ICT_AI_W6_Cami.git portfolio/2223107-cami/ICT_AI_W6_Cami
git submodule add https://github.com/2223107-cami/ICT_AI_W5_Cami.git portfolio/2223107-cami/ICT_AI_W5_Cami
git submodule add https://github.com/2223107-cami/ICT_AI2.0_Cami.git portfolio/2223107-cami/ICT_AI2.0_Cami
git submodule add https://github.com/2223107-cami/ICT_AI_W3_Cami.git portfolio/2223107-cami/ICT_AI_W3_Cami
git submodule add https://github.com/2223107-cami/ICT_AI_W2_Cami.git portfolio/2223107-cami/ICT_AI_W2_Cami
git submodule add https://github.com/2223107-cami/ICT_AI_W1_Cami.git portfolio/2223107-cami/ICT_AI_W1_Cami
git submodule add https://github.com/Koodybiglookyea/draw.git portfolio/Koodybiglookyea/draw
git submodule add https://github.com/Koodybiglookyea/piano.git portfolio/Koodybiglookyea/piano
git submodule add https://github.com/Koodybiglookyea/music-game.git portfolio/Koodybiglookyea/music-game
git submodule add https://github.com/Koodybiglookyea/8-ball-pool.git portfolio/Koodybiglookyea/8-ball-pool
git submodule add https://github.com/Koodybiglookyea/car.git portfolio/Koodybiglookyea/car
git submodule add https://github.com/Koodybiglookyea/UFCfightersalary.git portfolio/Koodybiglookyea/UFCfightersalary
git submodule add https://github.com/Koodybiglookyea/aparmentselling.git portfolio/Koodybiglookyea/aparmentselling
git submodule add https://github.com/Koodybiglookyea/calnomei.git portfolio/Koodybiglookyea/calnomei
git submodule add https://github.com/Koodybiglookyea/camera-project.git portfolio/Koodybiglookyea/camera-project
git submodule add https://github.com/Koodybiglookyea/KOODY5.git portfolio/Koodybiglookyea/KOODY5
git submodule add https://github.com/Koodybiglookyea/koody1.git portfolio/Koodybiglookyea/koody1
git submodule add https://github.com/Koodybiglookyea/word-game.git portfolio/Koodybiglookyea/word-game
git submodule add https://github.com/Koodybiglookyea/game2.0.git portfolio/Koodybiglookyea/game2.0
git submodule add https://github.com/Koodybiglookyea/stackblitz-starters-dvua41te.git portfolio/Koodybiglookyea/stackblitz-starters-dvua41te
git submodule add https://github.com/haha197/opendaygame_last.git portfolio/haha197/opendaygame_last
git submodule add https://github.com/haha197/Whatnight.git portfolio/haha197/Whatnight
git submodule add https://github.com/haha197/seclet_list.git portfolio/haha197/seclet_list
git submodule add https://github.com/haha197/hahahah.git portfolio/haha197/hahahah
git submodule add https://github.com/haha197/draw.git portfolio/haha197/draw
git submodule add https://github.com/haha197/openDayFishTwoPeople.git portfolio/haha197/openDayFishTwoPeople
git submodule add https://github.com/haha197/opendaygame_2.git portfolio/haha197/opendaygame_2
git submodule add https://github.com/haha197/openday_game.git portfolio/haha197/openday_game
git submodule add https://github.com/haha197/openday_gm.git portfolio/haha197/openday_gm
git submodule add https://github.com/haha197/STAND.git portfolio/haha197/STAND
git submodule add https://github.com/haha197/drawbroad_hehe.git portfolio/haha197/drawbroad_hehe
git submodule add https://github.com/haha197/stackblitz-starters-nwue149t.git portfolio/haha197/stackblitz-starters-nwue149t
git submodule add https://github.com/haha197/new_chat.git portfolio/haha197/new_chat
git submodule add https://github.com/haha197/jslearning.git portfolio/haha197/jslearning
git submodule add https://github.com/haha197/chat.git portfolio/haha197/chat
git submodule add https://github.com/Kory520/clicker-game.git portfolio/kory520/clicker-game
git submodule add https://github.com/kou1gn/stackblitz-instagram-screenshot-maker.git portfolio/kou1gn/stackblitz-instagram-screenshot-maker
git submodule add https://github.com/kou1gn/stackblitz-starters-chatroom.git portfolio/kou1gn/stackblitz-starters-chatroom
git submodule add https://github.com/kou1gn/20250912-1st-repo.git portfolio/kou1gn/20250912-1st-repo
git submodule add https://github.com/BARON1118/draw.git portfolio/BARON1118/draw
git submodule add https://github.com/BARON1118/WATER-4.git portfolio/BARON1118/WATER-4
git submodule add https://github.com/BARON1118/cam.git portfolio/BARON1118/cam
git submodule add https://github.com/BARON1118/kmb.git portfolio/BARON1118/kmb
git submodule add https://github.com/BARON1118/hksc-water2.git portfolio/BARON1118/hksc-water2
git submodule add https://github.com/BARON1118/stackblitz-starters-rjvwwbjg.git portfolio/BARON1118/stackblitz-starters-rjvwwbjg
git submodule add https://github.com/BARON1118/hksc-water.git portfolio/BARON1118/hksc-water
git submodule add https://github.com/BARON1118/stackblitz-hksc-daily.git portfolio/BARON1118/stackblitz-hksc-daily
git submodule add https://github.com/BARON1118/liftCounter.git portfolio/BARON1118/liftCounter
git submodule add https://github.com/BARON1118/cotd.git portfolio/BARON1118/cotd
git submodule add https://github.com/v1ann/block-blast.git portfolio/v1ann/block-blast
git submodule add https://github.com/v1ann/stackblitz-starters-e2li6724.git portfolio/v1ann/stackblitz-starters-e2li6724
git submodule add https://github.com/v1ann/2048.git portfolio/v1ann/2048
git submodule add https://github.com/v1ann/stackblitz-starters-e2li0529.git portfolio/v1ann/stackblitz-starters-e2li0529
git submodule add https://github.com/v1ann/stackblitz-starters-rd7a4qhx.git portfolio/v1ann/stackblitz-starters-rd7a4qhx
git submodule add https://github.com/v1ann/stackblitz-starters-gsypszfb.git portfolio/v1ann/stackblitz-starters-gsypszfb
git submodule add https://github.com/v1ann/stackblitz-0526.git portfolio/v1ann/stackblitz-0526
git submodule add https://github.com/v1ann/0522.git portfolio/v1ann/0522
git submodule add https://github.com/v1ann/stackblitz-0519-3.0.git portfolio/v1ann/stackblitz-0519-3.0
git submodule add https://github.com/v1ann/stackblitz-0519-2.0.git portfolio/v1ann/stackblitz-0519-2.0
git submodule add https://github.com/v1ann/stackblitz-0519.git portfolio/v1ann/stackblitz-0519
git submodule add https://github.com/v1ann/1505jump.git portfolio/v1ann/1505jump
git submodule add https://github.com/v1ann/speed.git portfolio/v1ann/speed
git submodule add https://github.com/v1ann/3.0waterfisheatshit.git portfolio/v1ann/3.0waterfisheatshit
git submodule add https://github.com/v1ann/stackblitz-starters-dhtjyxmq.git portfolio/v1ann/stackblitz-starters-dhtjyxmq
git submodule add https://github.com/v1ann/260428.git portfolio/v1ann/260428
git submodule add https://github.com/v1ann/chatroom.git portfolio/v1ann/chatroom
git submodule add https://github.com/v1ann/1.git portfolio/v1ann/1
git submodule add https://github.com/EmilyLau41/together_draw.git portfolio/EmilyLau41/together_draw
git submodule add https://github.com/EmilyLau41/magic.git portfolio/EmilyLau41/magic
git submodule add https://github.com/EmilyLau41/2D_Map.git portfolio/EmilyLau41/2D_Map
git submodule add https://github.com/EmilyLau41/hksc-interactive-map.git portfolio/EmilyLau41/hksc-interactive-map
git submodule add https://github.com/EmilyLau41/cooking.git portfolio/EmilyLau41/cooking
git submodule add https://github.com/EmilyLau41/kill_furit.git portfolio/EmilyLau41/kill_furit
git submodule add https://github.com/EmilyLau41/buy_app.git portfolio/EmilyLau41/buy_app
git submodule add https://github.com/EmilyLau41/cake-game.git portfolio/EmilyLau41/cake-game
git submodule add https://github.com/EmilyLau41/Math-.git portfolio/EmilyLau41/Math-
git submodule add https://github.com/EmilyLau41/CHAT-ROOM.git portfolio/EmilyLau41/CHAT-ROOM
git submodule add https://github.com/EmilyLau41/skyapp.git portfolio/EmilyLau41/skyapp
git submodule add https://github.com/EmilyLau41/cheat-room.git portfolio/EmilyLau41/cheat-room
git submodule add https://github.com/EmilyLau41/-.git portfolio/EmilyLau41/-
git submodule add https://github.com/EmilyLau41/emotionapp.git portfolio/EmilyLau41/emotionapp
git submodule add https://github.com/giovanniuufj/Aemeath.git portfolio/giovanniuufj/Aemeath
git submodule add https://github.com/giovanniuufj/pet.git portfolio/giovanniuufj/pet
git submodule add https://github.com/2526452-cmd/GIF-.git portfolio/2526452-cmd/GIF-
git submodule add https://github.com/2526452-cmd/theworld_tao.git portfolio/2526452-cmd/theworld_tao
git submodule add https://github.com/2526452-cmd/q1.git portfolio/2526452-cmd/q1
git submodule add https://github.com/2526452-cmd/hksc-interactive-map.git portfolio/2526452-cmd/hksc-interactive-map
git submodule add https://github.com/2526452-cmd/DIGITAL-CURATOR-SYSTEM.git portfolio/2526452-cmd/DIGITAL-CURATOR-SYSTEM
git submodule add https://github.com/2526452-cmd/-stackblitz-starters-59fe7jfm.git portfolio/2526452-cmd/-stackblitz-starters-59fe7jfm
git submodule add https://github.com/2526452-cmd/stackblitz-starters-9sgg9xve.git portfolio/2526452-cmd/stackblitz-starters-9sgg9xve
git submodule add https://github.com/2526452-cmd/stackblitz-starters-sxl7h93b.git portfolio/2526452-cmd/stackblitz-starters-sxl7h93b
git submodule add https://github.com/2526452-cmd/leave-slip.git portfolio/2526452-cmd/leave-slip
git submodule add https://github.com/2526452-cmd/6-2-2026.git portfolio/2526452-cmd/6-2-2026
git submodule add https://github.com/2526452-cmd/-.git portfolio/2526452-cmd/-
git submodule add https://github.com/2526452-cmd/q3-hk-.git portfolio/2526452-cmd/q3-hk-
git submodule add https://github.com/2526452-cmd/Q4-HKSC-FRIEND.git portfolio/2526452-cmd/Q4-HKSC-FRIEND
git submodule add https://github.com/2526453/song-recs.git portfolio/2526453/song-recs
git submodule add https://github.com/2526453/wiggly-paint.git portfolio/2526453/wiggly-paint
git submodule add https://github.com/2526453/green-aim.git portfolio/2526453/green-aim
git submodule add https://github.com/2526453/rage-quit.git portfolio/2526453/rage-quit
git submodule add https://github.com/2526453/alienmeow.git portfolio/2526453/alienmeow
git submodule add https://github.com/2526453/i-need-ur-locations.git portfolio/2526453/i-need-ur-locations
git submodule add https://github.com/2526453/chatroom-but-GREEEEEEEEEEEN.git portfolio/2526453/chatroom-but-GREEEEEEEEEEEN
git submodule add https://github.com/2526453/weeeeeeeeeeee.git portfolio/2526453/weeeeeeeeeeee
git submodule add https://github.com/2526453/meow.git portfolio/2526453/meow
git submodule add https://github.com/2526454-ship-it/math-quiz.git portfolio/2526454-ship-it/math-quiz
git submodule add https://github.com/2526454-ship-it/stackblitz-starters-nbdwaf6f.git portfolio/2526454-ship-it/stackblitz-starters-nbdwaf6f
git submodule add https://github.com/2526454-ship-it/Gamble-for-good.git portfolio/2526454-ship-it/Gamble-for-good
git submodule add https://github.com/2526454-ship-it/NPCTGT.git portfolio/2526454-ship-it/NPCTGT
git submodule add https://github.com/2526454-ship-it/CW-chcicken-Warfare.git portfolio/2526454-ship-it/CW-chcicken-Warfare
git submodule add https://github.com/2526454-ship-it/my-eng-persent.git portfolio/2526454-ship-it/my-eng-persent
git submodule add https://github.com/2526454-ship-it/GT.git portfolio/2526454-ship-it/GT
git submodule add https://github.com/2526454-ship-it/ni.git portfolio/2526454-ship-it/ni
git submodule add https://github.com/hayden626/Toronto-Raptors.git portfolio/hayden626/Toronto-Raptors
git submodule add https://github.com/hayden626/black-sound.git portfolio/hayden626/black-sound
git submodule add https://github.com/hayden626/drew.git portfolio/hayden626/drew
git submodule add https://github.com/hayden626/NEURAL_MEMO.git portfolio/hayden626/NEURAL_MEMO
git submodule add https://github.com/hayden626/NASA.git portfolio/hayden626/NASA
git submodule add https://github.com/hayden626/cam.git portfolio/hayden626/cam
git submodule add https://github.com/hayden626/universe.git portfolio/hayden626/universe
git submodule add https://github.com/hayden626/hong-kong.git portfolio/hayden626/hong-kong
git submodule add https://github.com/hayden626/Nba.git portfolio/hayden626/Nba
git submodule add https://github.com/hayden626/po-1.git portfolio/hayden626/po-1
git submodule add https://github.com/hayden626/game-BOS.git portfolio/hayden626/game-BOS
git submodule add https://github.com/hayden626/game-BOSS.git portfolio/hayden626/game-BOSS
git submodule add https://github.com/hayden626/Hayden-mugffd.git portfolio/hayden626/Hayden-mugffd
git submodule add https://github.com/hayden626/stackblitz-starters-lvgcssag.git portfolio/hayden626/stackblitz-starters-lvgcssag
git submodule add https://github.com/hayden626/4M24.git portfolio/hayden626/4M24
git submodule add https://github.com/ethanhksc0930/evil_copy_of_cardboardsynth.git portfolio/ethanhksc0930/evil_copy_of_cardboardsynth
git submodule add https://github.com/ethanhksc0930/piano-hehehehehhahhahhahahhahaaahhahahaha.git portfolio/ethanhksc0930/piano-hehehehehhahhahhahahhahaaahhahahaha
git submodule add https://github.com/ethanhksc0930/test-.git portfolio/ethanhksc0930/test-
git submodule add https://github.com/ethanhksc0930/audio-editor.git portfolio/ethanhksc0930/audio-editor
git submodule add https://github.com/ethanhksc0930/Sigma-Oscilloscope-simulator.git portfolio/ethanhksc0930/Sigma-Oscilloscope-simulator
git submodule add https://github.com/ethanhksc0930/Buggy-music_explorer.git portfolio/ethanhksc0930/Buggy-music_explorer
git submodule add https://github.com/ethanhksc0930/Simple-drum-machine.git portfolio/ethanhksc0930/Simple-drum-machine
git submodule add https://github.com/ethanhksc0930/simple-Hz-generator.git portfolio/ethanhksc0930/simple-Hz-generator
git submodule add https://github.com/2526465-lgtm/on9-clicker-game.git portfolio/2526465-lgtm/on9-clicker-game
git submodule add https://github.com/2526465-lgtm/on9-game.git portfolio/2526465-lgtm/on9-game
git submodule add https://github.com/2223176-tech/TWO-GOLDEN-APPLE-.git portfolio/2223176-tech/TWO-GOLDEN-APPLE-
git submodule add https://github.com/2223176-tech/uno-game.git portfolio/2223176-tech/uno-game
git submodule add https://github.com/2223176-tech/KJMRF-OAJFGPOANDfgbwsrfgbwrebvswdfb.git portfolio/2223176-tech/KJMRF-OAJFGPOANDfgbwsrfgbwrebvswdfb
git submodule add https://github.com/2223176-tech/racr-track-daniel-wong-.git portfolio/2223176-tech/racr-track-daniel-wong-
git submodule add https://github.com/2223176-tech/nba-daniel.git portfolio/2223176-tech/nba-daniel
git submodule add https://github.com/2223176-tech/stackblitz-starters-6xsn86o2nbanbanbanba.git portfolio/2223176-tech/stackblitz-starters-6xsn86o2nbanbanbanba
git submodule add https://github.com/2223176-tech/one-game.git portfolio/2223176-tech/one-game
git submodule add https://github.com/2223176-tech/nba-marks-scot.git portfolio/2223176-tech/nba-marks-scot
git submodule add https://github.com/2223176-tech/nba-marks-sc.git portfolio/2223176-tech/nba-marks-sc
git submodule add https://github.com/2526470-collab/draw-Supabase.git portfolio/2526470-collab/draw-Supabase
git submodule add https://github.com/2526470-collab/mywebsite.git portfolio/2526470-collab/mywebsite
git submodule add https://github.com/2526470-collab/emoji-game.git portfolio/2526470-collab/emoji-game
git submodule add https://github.com/2526470-collab/OC-background-generator.git portfolio/2526470-collab/OC-background-generator
git submodule add https://github.com/2526470-collab/hk-weather.git portfolio/2526470-collab/hk-weather
git submodule add https://github.com/2526470-collab/magic-GAME.git portfolio/2526470-collab/magic-GAME
git submodule add https://github.com/2526470-collab/drawing.git portfolio/2526470-collab/drawing
git submodule add https://github.com/2526470-collab/3d.git portfolio/2526470-collab/3d
git submodule add https://github.com/2526470-collab/hk-public-holiday.git portfolio/2526470-collab/hk-public-holiday
git submodule add https://github.com/2526470-collab/-messages.git portfolio/2526470-collab/-messages
git submodule add https://github.com/2526470-collab/hksc-woman-toilet.git portfolio/2526470-collab/hksc-woman-toilet
git submodule add https://github.com/2526470-collab/Krystal.git portfolio/2526470-collab/Krystal
git submodule add https://github.com/crazyjayhm/Adrian-7.git portfolio/crazyjayhm/Adrian-7
git submodule add https://github.com/crazyjayhm/Adrian-6.git portfolio/crazyjayhm/Adrian-6
git submodule add https://github.com/crazyjayhm/game-3.git portfolio/crazyjayhm/game-3
git submodule add https://github.com/crazyjayhm/Sports-field-circle-keyboard-race.git portfolio/crazyjayhm/Sports-field-circle-keyboard-race
git submodule add https://github.com/crazyjayhm/camera-01.git portfolio/crazyjayhm/camera-01
git submodule add https://github.com/crazyjayhm/weather-2.git portfolio/crazyjayhm/weather-2
git submodule add https://github.com/crazyjayhm/Game-1.git portfolio/crazyjayhm/Game-1
git submodule add https://github.com/crazyjayhm/game.git portfolio/crazyjayhm/game
git submodule add https://github.com/crazyjayhm/ai-2.git portfolio/crazyjayhm/ai-2
git submodule add https://github.com/crazyjayhm/adrian-.git portfolio/crazyjayhm/adrian-
git submodule add https://github.com/crazyjayhm/adrian-ai.git portfolio/crazyjayhm/adrian-ai
git submodule add https://github.com/crazyjayhm/-.git portfolio/crazyjayhm/-